CONSUMER_KEY = '_9Ty87I4e6x4p0ogfVw6SA'
CONSUMER_SECRET = '3lcv1H445pT8zJB45uWmCxIxDvI'
TOKEN = 'ArdXkl7yDB0Hk1LIR3uXVgcqrNhum0O4'
TOKEN_SECRET = 'WjNcTLnReKVK4en1toYfwBx7nQw'

def getKeys():
	return (CONSUMER_KEY,CONSUMER_SECRET,TOKEN,TOKEN_SECRET)
