/*
 * Steps for loading the data
 *  - Download and install Postgres on your machine (see www.postgres.org)
 *  - Download data files and script
 *  - Start Postgres and create a database called SQLBook
 *  - Replace all instances of $load_dir$ with the correct path
 *  - Run this script from inside Postgres
 */
 
CREATE TABLE Calendar (
	Date date NOT NULL,
	ISO varchar(10) NOT NULL,
	datenum int NOT NULL,
	DOW char(3) NOT NULL,
	DOWint smallint NOT NULL,
	Year smallint NOT NULL,
	Month smallint NOT NULL,
	DOM smallint NOT NULL,
	MonthAbbr char(3) NOT NULL,
	DOY smallint NOT NULL,
	Mondays smallint NOT NULL,
	Tuesdays smallint NOT NULL,
	Wednesdays smallint NOT NULL,
	Thursdays smallint NOT NULL,
	Fridays smallint NOT NULL,
	Saturdays smallint NOT NULL,
	Sundays smallint NOT NULL,
	NumHolidays int NOT NULL,
	HolidayName varchar(255) NULL,
	HolidayType varchar(9) NULL,
	hol_National varchar(255) NULL,
	hol_Minor varchar(255) NULL,
	hol_Christian varchar(255) NULL,
	hol_Jewish varchar(255) NULL,
	hol_Muslim varchar(255) NULL,
	hol_Chinese varchar(255) NULL,
	hol_Other varchar(255) NULL
) ;

COPY Calendar FROM '$load_dir$Calendar.txt'
    WITH HEADER NULL 'NULL' DELIMITER '	' CSV;

CREATE TABLE Campaigns (
	CampaignId int NOT NULL PRIMARY KEY,
	CampaignName varchar(50) NOT NULL,
	Channel varchar(50) NOT NULL,
	Discount int NOT NULL,
	FreeShppingFlag char(1) NOT NULL
) ;


COPY Campaigns FROM '$load_dir$Campaigns.txt'
    WITH HEADER NULL 'NULL' DELIMITER '	' CSV;


CREATE TABLE Customers (
	CustomerId int NOT NULL PRIMARY KEY,
	HouseholdId int NOT NULL,
	Gender varchar(50) NOT NULL,
	FirstName varchar(50) NOT NULL
) ;

COPY Customers FROM '$load_dir$Customers.txt'
    WITH HEADER NULL 'NULL' DELIMITER '	' CSV;


CREATE TABLE OrderLines (
	OrderLineId int NOT NULL PRIMARY KEY,
	OrderId int NOT NULL,
	ProductId int NULL,
	ShipDate date NOT NULL,
	BillDate date NOT NULL,
	UnitPrice money NOT NULL,
	NumUnits int NOT NULL,
	TotalPrice money NOT NULL
) ;


COPY OrderLines FROM '$load_dir$OrderLines.txt'
    WITH HEADER NULL 'NULL' DELIMITER '	' CSV;


CREATE TABLE Orders (
	OrderId int NOT NULL PRIMARY KEY,
	CustomerId int NOT NULL,
	CampaignId int NOT NULL,
	OrderDate date NOT NULL,
	City varchar(50) NOT NULL,
	State varchar(50) NOT NULL,
	ZipCode varchar(50) NOT NULL,
	PaymentType varchar(50) NOT NULL,
	TotalPrice money NOT NULL,
	NumOrderLines int NOT NULL,
	NumUnits int NOT NULL
) ;


COPY Orders FROM '$load_dir$Orders.txt'
    WITH HEADER NULL 'NULL' DELIMITER '	' ENCODING 'LATIN1'  CSV;


CREATE TABLE Products (
	ProductId int NOT NULL PRIMARY KEY,
	Name varchar(50) NOT NULL,
	GroupCode varchar(50) NOT NULL,
	GroupName varchar(50) NOT NULL,
	IsInStock char(1) NOT NULL,
	FullPrice money NOT NULL,
    Asin char(10) NOT NULL
) ;



COPY Products FROM '$load_dir$Products.txt'
    WITH HEADER NULL 'NULL' DELIMITER '	' CSV;


CREATE TABLE  Subscribers (
  SubscriberId int NOT NULL primary key,
  RatePlan varchar(6) NOT NULL,
  MonthlyFee float NOT NULL,
  Market varchar(10) NOT NULL,
  Channel varchar(6) NOT NULL,
  StartDate date default NULL,
  StopDate date default NULL,
  StopType char(1),
  Tenure int default NULL,
  IsActive int default NULL
);

COPY Subscribers FROM '$load_dir$Subscribers.txt'
    WITH HEADER NULL 'NULL' DELIMITER '	' CSV;


create table ZipCensus (
    state varchar(255),
    zcta5 varchar(255),
    ZIPName varchar(255),
    County varchar(255),
    pctcnty decimal(5, 4),
    Fipco int,
    FipCo2 int,
    pctState decimal(5, 4),
    AltZIPs varchar(255),
    NaltZIPs int,
    Stab varchar(255),
    IntPtLat float,
    IntPtLon float,
    LandSQMI float,
    AreaSQMI float,
    TotPopsf1 int,
    esriid int,
    geoid varchar(255),
    AreaName varchar(255),
    LogRecno int,
    TotPop int,
    Age0_4 int,
    pctAge0_4 decimal(5, 4),
    Age5_9 int,
    pctAge5_9 decimal(5, 4),
    Age10_14 int,
    pctAge10_14 decimal(5, 4),
    Age15_19 int,
    pctAge15_19 decimal(5, 4),
    Age20_24 int,
    pctAge20_24 decimal(5, 4),
    Age25_34 int,
    pctAge25_34 decimal(5, 4),
    Age35_44 int,
    pctAge35_44 decimal(5, 4),
    Age45_54 int,
    pctAge45_54 decimal(5, 4),
    Age55_59 int,
    pctAge55_59 decimal(5, 4),
    Age60_64 int,
    pctAge60_64 decimal(5, 4),
    Age65_74 int,
    pctAge65_74 decimal(5, 4),
    Age75_84 int,
    pctAge75_84 decimal(5, 4),
    Over85 int,
    pctOver85 decimal(5, 4),
    MedianAge float,
    Over5 int,
    pctOver5 decimal(5, 4),
    Over15 int,
    pctOver15 decimal(5, 4),
    Under18 int,
    pctUnder18 decimal(5, 4),
    Over18 int,
    pctOver18 decimal(5, 4),
    Over21 int,
    pctOver21 decimal(5, 4),
    Over25 int,
    pctOver25 decimal(5, 4),
    Over62 int,
    pctOver62 decimal(5, 4),
    Over65 int,
    pctOver65 decimal(5, 4),
    Males int,
    pctMales decimal(5, 4),
    Over18Males int,
    pctOver18Males decimal(5, 4),
    Over65Males int,
    pctOver65Males decimal(5, 4),
    Females int,
    pctFemales decimal(5, 4),
    Over18Females int,
    pctOver18Females decimal(5, 4),
    Over65Females int,
    pctOver65Females decimal(5, 4),
    OneRace int,
    pctOneRace decimal(5, 4),
    White1 int,
    pctWhite1 decimal(5, 4),
    Black1 int,
    pctBlack1 decimal(5, 4),
    Indian1 int,
    pctIndian1 decimal(5, 4),
    Asian1 int,
    pctAsian1 decimal(5, 4),
    HawnPI1 int,
    pctHawnPI1 decimal(5, 4),
    Other1 int,
    pctOther1 decimal(5, 4),
    MultiRace int,
    pctMultiRace decimal(5, 4),
    White2 int,
    pctWhite2 decimal(5, 4),
    Black2 int,
    pctBlack2 decimal(5, 4),
    Indian2 int,
    pctIndian2 decimal(5, 4),
    Asian2 int,
    pctAsian2 decimal(5, 4),
    HawnPI2 int,
    pctHawnPI2 decimal(5, 4),
    Other2 int,
    pctOther2 decimal(5, 4),
    HispanicPop int,
    pctHispanicPop decimal(5, 4),
    NonHispPop int,
    pctNonHispPop decimal(5, 4),
    NonHispWhite int,
    pctNonHispWhite decimal(5, 4),
    NonHispBlack int,
    pctNonHispBlack decimal(5, 4),
    NonHispAmInd int,
    pctNonHispAmInd decimal(5, 4),
    NonHispAsian int,
    pctNonHispAsian decimal(5, 4),
    NonHispHawnPI int,
    pctNonHispHawnPI decimal(5, 4),
    TotHHs int,
    HHInc0 int,
    pctHHInc0 decimal(5, 4),
    HHInc10 int,
    pctHHInc10 decimal(5, 4),
    HHInc15 int,
    pctHHInc15 decimal(5, 4),
    HHInc25 int,
    pctHHInc25 decimal(5, 4),
    HHInc35 int,
    pctHHInc35 decimal(5, 4),
    HHInc50 int,
    pctHHInc50 decimal(5, 4),
    HHInc75 int,
    pctHHInc75 decimal(5, 4),
    HHInc100 int,
    pctHHInc100 decimal(5, 4),
    HHInc150 int,
    pctHHInc150 decimal(5, 4),
    HHInc200 int,
    pctHHInc200 decimal(5, 4),
    MedianHHInc money,
    AvgHHInc money,
    NumHHEarnings int,
    pctNumHHEarnings decimal(5, 4),
    AvgHHEarnings money,
    NumHHSocSec int,
    pctNumHHSocSec decimal(5, 4),
    AvgHHSocSec money,
    NumHHRetInc int,
    pctNumHHRetInc decimal(5, 4),
    AvgHHRetInc money,
    NumHHSuppSecInc int,
    pctNumHHSuppSecInc decimal(5, 4),
    AvgHHSuppSecInc money,
    NumHHPubAssist int,
    pctNumHHPubAssist decimal(5, 4),
    AvgHHPubAssist money,
    NumHHFoodStmp int,
    pctNumHHFoodStmp decimal(5, 4),
    FamHHs int,
    pctFamHHs decimal(5, 4),
    FamHHInc0 int,
    pctFamHHInc0 decimal(5, 4),
    FamHHInc10 int,
    pctFamHHInc10 decimal(5, 4),
    FamHHInc15 int,
    pctFamHHInc15 decimal(5, 4),
    FamHHInc25 int,
    pctFamHHInc25 decimal(5, 4),
    FamHHInc35 int,
    pctFamHHInc35 decimal(5, 4),
    FamHHInc50 int,
    pctFamHHInc50 decimal(5, 4),
    FamHHInc75 int,
    pctFamHHInc75 decimal(5, 4),
    FamHHInc100 int,
    pctFamHHInc100 decimal(5, 4),
    FamHHInc150 int,
    pctFamHHInc150 decimal(5, 4),
    FamHHInc200 int,
    pctFamHHInc200 decimal(5, 4),
    MedianFamInc money,
    AvgFamInc money,
    PCI money,
    NonFamHHs int,
    pctNonFamHHs decimal(5, 4),
    MedianNonFamInc money,
    AvgNonFamInc money,
    FullTimeWorkers int,
    FullTimeWorkersMale int,
    pctFullTimeWorkersMale decimal(5, 4),
    FullTimeWorkersFemale int,
    pctFullTimeWorkersFemale decimal(5, 4),
    MedianEarnings money,
    MedianEarningsMale money,
    MedianEarningsFemale money,
    PovUniverse int,
    Poor int,
    pctPoor decimal(5, 4),
    PovUniverseUnder18 int,
    PoorUnder18 int,
    PctPoorUnder18 decimal(5, 4),
    PovUniverse18_64 int,
    Poor18to64 int,
    pctPoor18to64 decimal(5, 4),
    PovUniverseOver65 int,
    PoorOver65 int,
    pctPoorOver65 decimal(5, 4),
    PovUniverseFamilyPop int,
    pctFamilyPopPoor decimal(5, 4),
    PovUniverseUnrelated int,
    PoorInFamily int,
    pctPoorInFamily decimal(5, 4),
    PoorUnrelated int,
    pctPoorUnrelated decimal(5, 4),
    PovRatioUnderHalf int,
    pctPovRatioUnderHalf decimal(5, 4),
    PovRatiov5tov99 int,
    pctPovRatiov5tov99 decimal(5, 4),
    PovRatio1to2 int,
    pctPovRatio1to2 decimal(5, 4),
    PovRatioOver2 int,
    pctPovRatioOver2 decimal(5, 4),
    Over16 int,
    LaborForce int,
    pctLaborForce decimal(5, 4),
    CivLabForce int,
    pctCivLabForce decimal(5, 4),
    EmployedCLF int,
    pctEmployedCLF decimal(5, 4),
    UnemployedCLF int,
    pctUnemployedCLF decimal(5, 4),
    Military int,
    pctMilitary decimal(5, 4),
    NotInLF int,
    pctNotInLF decimal(5, 4),
    Over16Females int,
    pctOver16Females decimal(5, 4),
    LaborForceFemales int,
    pctLaborForceFemales decimal(5, 4),
    CivLabForceFemales int,
    pctCivLabForceFemales decimal(5, 4),
    EmployedFemales int,
    pctEmployedFemales decimal(5, 4),
    OwnKidsUnder6 int,
    OwnKidsU6AllPrntsWk int,
    pctOwnKidsU6AllPrntsWk decimal(5, 4),
    OwnKidsOver6 int,
    OwnKidsO6AllPrntsWk int,
    pctOwnKidsO6AllPrntsWk decimal(5, 4),
    Worker16 int,
    Commuters int,
    pctCommuters decimal(5, 4),
    DriveAlone int,
    pctDriveAlone decimal(5, 4),
    Carpool int,
    pctCarpool decimal(5, 4),
    PublicTrans int,
    pctPublicTrans decimal(5, 4),
    WalkToWork int,
    pctWalkToWork decimal(5, 4),
    OtherCommute int,
    pctOtherCommute decimal(5, 4),
    WorkAtHome int,
    pctWorkAtHome decimal(5, 4),
    AvgCommute float,
    ManProfOccs int,
    pctManProfOccs decimal(5, 4),
    ServiceOccs int,
    pctServiceOccs decimal(5, 4),
    SalesOffOccs int,
    pctSalesOffOccs decimal(5, 4),
    FarmFishOccs int,
    pctFarmFishOccs decimal(5, 4),
    ConsOccs int,
    pctConsOccs decimal(5, 4),
    TransOccs int,
    pctTransOccs decimal(5, 4),
    Agriculture int,
    pctAgriculture decimal(5, 4),
    Construction int,
    pctConstruction decimal(5, 4),
    Manufacturing int,
    pctManufacturing decimal(5, 4),
    WholesaleTrade int,
    pctWholesaleTrade decimal(5, 4),
    RetailTrade int,
    pctRetailTrade decimal(5, 4),
    Transportation int,
    pctTransportation decimal(5, 4),
    Information int,
    pctInformation decimal(5, 4),
    Finance_Ins int,
    pctFinance_Ins decimal(5, 4),
    Professional int,
    pctProfessional decimal(5, 4),
    Educ_Health_SocSvcs int,
    pctEduc_Health_SocSvcs decimal(5, 4),
    RecreationEtc int,
    pctRecreationEtc decimal(5, 4),
    OtherIndustries int,
    pctOtherIndustries decimal(5, 4),
    PublicAdmin int,
    pctPublicAdmin decimal(5, 4),
    PrivWageWorkers int,
    pctPrivWageWorkers decimal(5, 4),
    GovWorkers int,
    pctGovWorkers decimal(5, 4),
    SelfEmpWorkers int,
    pctSelfEmpWorkers decimal(5, 4),
    UnpaidFamWorkers int,
    pctUnpaidFamWorkers decimal(5, 4),
    Families int,
    pctFamilies decimal(5, 4),
    FamsWithKids int,
    pctFamsWithKids decimal(5, 4),
    MarriedCouples int,
    pctMarriedCouples decimal(5, 4),
    CouplesWithKids int,
    pctCouplesWithKids decimal(5, 4),
    SingleMaleFamilies int,
    pctSingleMaleFamilies decimal(5, 4),
    SingleFathers int,
    pctSingleFathers decimal(5, 4),
    SingleFemaleFamilies int,
    pctSingleFemaleFamilies decimal(5, 4),
    SingleMothers int,
    pctSingleMothers decimal(5, 4),
    LivingAlone int,
    pctLivingAlone decimal(5, 4),
    Over65Alone int,
    pctOver65Alone decimal(5, 4),
    HHsWithKids int,
    pctHHsWithKids decimal(5, 4),
    HHsWithElders int,
    pctHHsWithElders decimal(5, 4),
    AvgHHSize float,
    AvgFamSize float,
    HHPop int,
    pctHHPop decimal(5, 4),
    FamHHpop int,
    pctFamHHpop decimal(5, 4),
    NonFamHHpop int,
    pctNonFamHHpop decimal(5, 4),
    GrpQuarters int,
    pctGrpQuarters decimal(5, 4),
    Householder int,
    pctHouseholder decimal(5, 4),
    Spouse int,
    pctSpouse decimal(5, 4),
    Child int,
    pctChild decimal(5, 4),
    OtherRelative int,
    pctOtherRelative decimal(5, 4),
    NonRelative int,
    pctNonRelative decimal(5, 4),
    UnmarriedPartner int,
    pctUnmarriedPartner decimal(5, 4),
    UMPartnerHHsPerK int,
    NeverMarried int,
    pctNeverMarried decimal(5, 4),
    Married int,
    pctMarried decimal(5, 4),
    Separated int,
    pctSeparated decimal(5, 4),
    Widowed int,
    pctWidowed decimal(5, 4),
    Divorced int,
    pctDivorced decimal(5, 4),
    Women15to50 int,
    UnmarriedWomen15to50 int,
    pctUnmarriedWomen15to50 decimal(5, 4),
    WomenGivingBirth int,
    pctWomenGivingBirth decimal(5, 4),
    UnmarriedGivingBirth int,
    pctUnmarriedGivingBirth decimal(5, 4),
    Women15to19 int,
    pctWomen15to19 decimal(5, 4),
    Women20to34 int,
    pctWomen20to34 decimal(5, 4),
    Women35to50 int,
    pctWomen35to50 decimal(5, 4),
    UnmarriedGivingBirthPerk int,
    GivingBirthPerk int,
    BirthRate15_19 int,
    BirthRate20_34 int,
    BirthRate35_50 int,
    GrandPrntsLvngWithGrndkid int,
    GrandPrntsCaring int,
    pctGrandPrntsCaring decimal(5, 4),
    GrandPrntsCaringLT1 int,
    pctGrandPrntsCaringLT1 decimal(5, 4),
    GrandPrntsCaring1or2 int,
    pctGrandPrntsCaring1or2 decimal(5, 4),
    GrandPrntsCaring3or4 int,
    pctGrandPrntsCaring3or4 decimal(5, 4),
    GrandPrntsCaring5orMore int,
    pctGrandPrntsCaring5orMore decimal(5, 4),
    Over3 int,
    EnrolledOver3 int,
    pctEnrolledOver3 decimal(5, 4),
    InNursery int,
    pctInNursery decimal(5, 4),
    InKindergarten int,
    pctInKindergarten decimal(5, 4),
    InElementary int,
    pctInElementary decimal(5, 4),
    InHighSchool int,
    pctInHighSchool decimal(5, 4),
    InCollege int,
    pctInCollege decimal(5, 4),
    LessThan9th int,
    pctLessThan9th decimal(5, 4),
    SomeHighSchool int,
    pctSomeHighSchool decimal(5, 4),
    HighSchool int,
    pctHighSchool decimal(5, 4),
    SomeCollege int,
    pctSomeCollege decimal(5, 4),
    Associates int,
    pctAssociates decimal(5, 4),
    Bachelors int,
    pctBachelors decimal(5, 4),
    GradProf int,
    pctGradProf decimal(5, 4),
    HighSchoolOrMore int,
    pctHighSchoolOrMore decimal(5, 4),
    Bachelorsormore int,
    pctBachelorsormore decimal(5, 4),
    Civilian int,
    pctCivilian decimal(5, 4),
    Veteran int,
    pctVeteran decimal(5, 4),
    TotPopNonInst int,
    Disabled int,
    pctDisabled decimal(5, 4),
    NonInstUnder18 int,
    pctNonInstUnder18 decimal(5, 4),
    DisabledUnder18 int,
    pctDisabledUnder18 decimal(5, 4),
    NonInst18_64 int,
    pctNonInst18_64 decimal(5, 4),
    Disabled18_64 int,
    pctDisabled18_64 decimal(5, 4),
    NonInstOver65 int,
    pctNonInstOver65 decimal(5, 4),
    DisabledElder int,
    pctDisabledElder decimal(5, 4),
    Over1 int,
    SameHouse int,
    pctSameHouse decimal(5, 4),
    DiffHouse int,
    pctDiffHouse decimal(5, 4),
    DiffHouseSameCounty int,
    pctDiffHouseSameCounty decimal(5, 4),
    DiffCounty int,
    pctDiffCounty decimal(5, 4),
    DiffCntySameState int,
    pctDiffCntySameState decimal(5, 4),
    DiffState int,
    pctDiffState decimal(5, 4),
    LivedAbroad int,
    pctLivedAbroad decimal(5, 4),
    USNative int,
    pctUSNative decimal(5, 4),
    BornInUS int,
    pctBornInUS decimal(5, 4),
    BornInCurrState int,
    pctBornInCurrState decimal(5, 4),
    BornInDiffState int,
    pctBornInDiffState decimal(5, 4),
    BornAbroad int,
    pctBornAbroad decimal(5, 4),
    ForeignBorn int,
    pctForeignBorn decimal(5, 4),
    Naturalized int,
    pctNaturalized decimal(5, 4),
    NonCitizen int,
    pctNonCitizen decimal(5, 4),
    BornOutsideUS int,
    pctBornOutsideUS decimal(5, 4),
    BornOutsideUSNative int,
    pctBornOutsideUSNative decimal(5, 4),
    NativeEnteredGE2000 int,
    pctNativeEnteredGE2000 decimal(5, 4),
    NativeEnteredLT2000 int,
    pctNativeEnteredLT2000 decimal(5, 4),
    FBEnteredGE2000 int,
    pctFBEnteredGE2000 decimal(5, 4),
    FBEnteredLT2000 int,
    pctFBEnteredLT2000 decimal(5, 4),
    FBMinusSea int,
    pctFBMinusSea decimal(5, 4),
    FBEurope int,
    pctFBEurope decimal(5, 4),
    FBAsia int,
    pctFBAsia decimal(5, 4),
    FBAfrica int,
    pctFBAfrica decimal(5, 4),
    FBOceania int,
    pctFBOceania decimal(5, 4),
    FBLatinAmerica int,
    pctFBLatinAmerica decimal(5, 4),
    FBNorthAmerica int,
    pctFBNorthAmerica decimal(5, 4),
    EnglishOnly int,
    pctEnglishOnly decimal(5, 4),
    OthLang int,
    pctOthLang decimal(5, 4),
    OthLangEnglishLTD int,
    pctOthLangEnglishLTD decimal(5, 4),
    Spanish int,
    pctSpanish decimal(5, 4),
    SpanishEnglishLTD int,
    pctSpanishEnglishLTD decimal(5, 4),
    TotHUs int,
    OccHUs int,
    pctOccHUs decimal(5, 4),
    OwnerOcc int,
    pctOwnerOcc decimal(5, 4),
    RenterOcc int,
    pctRenterOcc decimal(5, 4),
    AvgOwnerHHSize float,
    AvgRenterHHSize float,
    VacHUs int,
    pctVacHUs decimal(5, 4),
    VacantForSale int,
    pctVacantForSale decimal(5, 4),
    VacantForRent int,
    pctVacantForRent decimal(5, 4),
    VacantSeasonal int,
    pctVacantSeasonal decimal(5, 4),
    TotalOwnerUnits int,
    OwnerVacRate float,
    TotalRentalUnits int,
    RenterVacRate float,
    PersonsInOwnerUnits int,
    pctPersonsInOwnerUnits decimal(5, 4),
    PersonsInRenterUnits int,
    pctPersonsInRenterUnits decimal(5, 4),
    Units1 int,
    pctUnits1 decimal(5, 4),
    Units1Detached int,
    pctUnits1Detached decimal(5, 4),
    Units1Attached int,
    pctUnits1Attached decimal(5, 4),
    Units2 int,
    pctUnits2 decimal(5, 4),
    Units3_4 int,
    pctUnits3_4 decimal(5, 4),
    Units5_9 int,
    pctUnits5_9 decimal(5, 4),
    Units10_19 int,
    pctUnits10_19 decimal(5, 4),
    Units20up int,
    pctUnits20up decimal(5, 4),
    MobileHomes int,
    pctMobileHomes decimal(5, 4),
    BoatRV int,
    pctBoatRV decimal(5, 4),
    MobileHomesPerK int,
    Built2010orLater int,
    pctBuilt2010orLater decimal(5, 4),
    Built2000_2009 int,
    pctBuilt2000_2009 decimal(5, 4),
    Built1990_1999 int,
    pctBuilt1990_1999 decimal(5, 4),
    Built1980_1989 int,
    pctBuilt1980_1989 decimal(5, 4),
    Built1970_1979 int,
    pctBuilt1970_1979 decimal(5, 4),
    Built1960_1969 int,
    pctBuilt1960_1969 decimal(5, 4),
    Built1950_1959 int,
    pctBuilt1950_1959 decimal(5, 4),
    Built1940_1949 int,
    pctBuilt1940_1949 decimal(5, 4),
    BuiltBefore1940 int,
    pctBuiltBefore1940 decimal(5, 4),
    MovedIn2010orLater int,
    pctMovedIn2010orLater decimal(5, 4),
    MovedIn2000_2009 int,
    pctMovedIn2000_2009 decimal(5, 4),
    MovedIn1990_1999 int,
    pctMovedIn1990_1999 decimal(5, 4),
    MovedIn1980_1989 int,
    pctMovedIn1980_1989 decimal(5, 4),
    MovedIn1970_1979 int,
    pctMovedIn1970_1979 decimal(5, 4),
    MovedInBefore1969 int,
    pctMovedInBefore1969 decimal(5, 4),
    NoVehicles int,
    pctNoVehicles decimal(5, 4),
    Vehicles1 int,
    pctVehicles1 decimal(5, 4),
    Vehicles2 int,
    pctVehicles2 decimal(5, 4),
    VehiclesGE3 int,
    pctVehiclesGE3 decimal(5, 4),
    HHFUtilGas int,
    pctHHFUtilGas decimal(5, 4),
    HHFLPGas int,
    pctHHFLPGas decimal(5, 4),
    HHFElectric int,
    pctHHFElectric decimal(5, 4),
    HHFKerosene int,
    pctHHFKerosene decimal(5, 4),
    HHFCoal int,
    pctHHFCoal decimal(5, 4),
    HHFWood int,
    pctHHFWood decimal(5, 4),
    HHFSolar int,
    pctHHFSolar decimal(5, 4),
    HHFOther int,
    pctHHFOther decimal(5, 4),
    HHFNoFuel int,
    pctHHFNoFuel decimal(5, 4),
    NoPlumbing int,
    pctNoPlumbing decimal(5, 4),
    NoKitchen int,
    pctNoKitchen decimal(5, 4),
    NoPhone int,
    pctNoPhone decimal(5, 4),
    PersonsPerRoomLow int,
    pctPersonsPerRoomLow decimal(5, 4),
    PersonsPerRoomMedium int,
    pctPersonsPerRoomMedium decimal(5, 4),
    PersonsPerRoomHigh int,
    pctPersonsPerRoomHigh decimal(5, 4),
    HvalUnder50 int,
    pctHvalUnder50 decimal(5, 4),
    Hval50 int,
    pctHval50 decimal(5, 4),
    Hval100 int,
    pctHval100 decimal(5, 4),
    Hval150 int,
    pctHval150 decimal(5, 4),
    Hval200 int,
    pctHval200 decimal(5, 4),
    Hval300 int,
    pctHval300 decimal(5, 4),
    Hval500 int,
    pctHval500 decimal(5, 4),
    HvalOverMillion int,
    pctHvalOverMillion decimal(5, 4),
    MedianHValue money,
    AvgHValue money,
    HUsMort int,
    pctHUsMort decimal(5, 4),
    HUsMortOver30Pct int,
    pctHUsMortOver30Pct decimal(5, 4),
    MedianOwnerCostsMort money,
    HUsNoMort int,
    pctHUsNoMort decimal(5, 4),
    HUsNoMortOver30Pct int,
    pctHUsNoMortOver30Pct decimal(5, 4),
    MedianOwnerCostsNoMort money,
    CashRenter int,
    pctCashRenter decimal(5, 4),
    NoCashRenter int,
    pctNoCashRenter decimal(5, 4),
    MedianGrossRent money,
    AvgGrossRent money,
    CashRenterOver30Pct int,
    pctCashRenterOver30Pct decimal(5, 4),
    CashRenterOver750 int,
    pctCashRenterOver750 decimal(5, 4)
);



COPY ZipCensus FROM '$load_dir$ZipCensus.txt'
    WITH HEADER NULL '\N' DELIMITER '	' CSV;


CREATE TABLE ZipCounty (
    ZipCode char(5) NULL,
    Latitude real NULL,
    Longitude real NULL,
    POName varchar(50) NULL,
    ZipClass char(1) NULL,
    CountyFIPs char(10) NULL,
    State varchar(50) NULL,
    CountyName varchar(50) NULL,
    CountyPop int NULL,
    CountyHU int NULL,
    CountyLandAreaMiles real NULL,
    CountyWaterAreaMiles real NULL
);

COPY ZipCounty FROM '$load_dir$ZipCounty.txt'
    WITH HEADER NULL 'NULL' DELIMITER '	' ENCODING 'LATIN1'  CSV;


CREATE TABLE Reviews (
    ReviewId varchar(25) NOT NULL,
    Asin char(10) NOT NULL,
    ReviewerName varchar(50) NOT NULL,
    Helpful varchar(20) NOT NULL,
    UnixReviewTime int NOT NULL,
    ReviewText varchar(32768) NOT NULL,
    Overall decimal(3,2) NOT NULL,
    ReviewTime timestamp NOT NULL,
    Summary varchar(1024) NOT NULL
);

COPY Reviews FROM '$load_dir$Reviews.txt'
    WITH HEADER NULL 'NULL' DELIMITER E'\t' ENCODING 'LATIN1'  CSV;